version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASWORD: postgres
      - POSTGRES_DB: payload
    networks:
      - cms-network

  cms:
    build: .
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/payload
      - PAYLOAD_SECRET=e1057e0557c2f564cfd10ed7
      - PAYLOAD_CONFIG_PATH=src/payload.config.ts
      - WEB_URI=http://localhost:3000
    depends_on:
      - postgres
    volumes:
      - .:/app/src
    networks:
      - cms-network
      - bridge

volumes:
  dbdata:
    driver: local

networks:
  cms-network:
    driver: bridge
